### ISSUE TITLE
App Crashes When I Add Banner Ad On Real iOS Device

### ISSUE THREAD

**Issue by ECD10** [marcojak/MTAdmob#130]
**Describe the bug**
I'm adding banner ads. There is no problem with the simulator. Test ads are working. But when I test it on a real device, when I go to the page with the banner ad, the application closes. It's okay with interstitials and rewarded ads.

**Smartphone (please complete the following information):**
 - OS: iOS
 - Version 16.4

**Crash Log**
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: 	GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ @"85d735920f1bba293f5fc6d9b09bef21" ];
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: Swift
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: 	GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ @"85d735920f1bba293f5fc6d9b09bef21" ]
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: Objective-C
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: 	GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ @"85d735920f1bba293f5fc6d9b09bef21" ];
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: Swift
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: 	GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ @"85d735920f1bba293f5fc6d9b09bef21" ]
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: <Google> To get test ads on this device, set: 
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: <Google> To get test ads on this device, set: 
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: <Google> To get test ads on this device, set: 
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: Objective-C
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: 	GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ @"85d735920f1bba293f5fc6d9b09bef21" ];
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: Swift
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: 	GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ @"85d735920f1bba293f5fc6d9b09bef21" ]
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: Objective-C
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: 	GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ @"85d735920f1bba293f5fc6d9b09bef21" ];
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: Swift
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: 	GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ @"85d735920f1bba293f5fc6d9b09bef21" ]
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: Objective-C
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: 	GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ @"85d735920f1bba293f5fc6d9b09bef21" ];
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: Swift
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: 	GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ @"85d735920f1bba293f5fc6d9b09bef21" ]
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: Unhandled managed exception: Arg_NullReferenceException (System.NullReferenceException)
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: Unhandled managed exception: Arg_NullReferenceException (System.NullReferenceException)
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: Unhandled managed exception: Arg_NullReferenceException (System.NullReferenceException)
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:    at ObjCRuntime.Runtime.ThrowException(IntPtr )
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:    at UIKit.UIApplication.UIApplicationMain(Int32 , String[] , IntPtr , IntPtr )
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:    at UIKit.UIApplication.Main(String[] , Type , Type )
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:    at bebekgelisimi.Program.Main(String[] )
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:     HighFrequency = 1;
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:     bundleID = "com.encada.***";
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:     pid = 3027;
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: } state:0x1 events:45 mask:0x40000800
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:    at ObjCRuntime.Runtime.ThrowException(IntPtr )
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:    at UIKit.UIApplication.UIApplicationMain(Int32 , String[] , IntPtr , IntPtr )
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:    at UIKit.UIApplication.Main(String[] , Type , Type )
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:    at bebekgelisimi.Program.Main(String[] )
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:     HighFrequency = 1;
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:     bundleID = "com.encada.****";
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:     pid = 3027;
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: } state:0x1 events:45 mask:0x40000800
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:    at ObjCRuntime.Runtime.ThrowException(IntPtr )
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:    at UIKit.UIApplication.UIApplicationMain(Int32 , String[] , IntPtr , IntPtr )
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:    at UIKit.UIApplication.Main(String[] , Type , Type )
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:    at bebekgelisimi.Program.Main(String[] )
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:     HighFrequency = 1;
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:     bundleID = "com.encada.****";
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>:     pid = 3027;
Apr 22 02:25:06 bebekgelisimi[3027] <Notice>: } state:0x1 events:45 mask:0x40000800

**Comment by marcojak** [comment]
I think I know the problem as it seems I had the same on the MAUI version.
I'm going to fix it asap.

**Comment by darklance83** [comment]
> I think I know the problem as it seems I had the same on the MAUI version. I'm going to fix it asap.

Hi marcojack,

First of all thanks a lot to you and your contributors for making this Plugin possible, I came here with the same issue, I finished an app completely in .net MAUI for iOS and Android, the app runs fine on Android with ads banner beautifully but when I run it on iOS it laods for like 5 seconds on .NET purple screen and then crashes I hope you are able to solve this soon as I really want this app to be released soon, and I will give you a coffee for your hard work, once again thanks a lot!

**Comment by marcojak** [comment]
Hi @darklance83 ,
 thank you for your support.

Are you sure the latest version of the plugin (1.0.4) still gives the same issue?
Does it work on the simulator?
If you could provide a crash report, that would help me.
Meanwhile I'm testing it on my mac and iPad to see if I get the same issue

**Comment by darklance83** [comment]
Hi Marco,

I am using Visual Studio 2022 .net MAUI I am running the app on iPAD Pro
and my iPhone 11 I already made the app in Android Studio and it is already
published on the app store ->
https://play.google.com/store/apps/details?id=cw.dushifm.dushifm889&hl=en_US&gl=US
and now I am trying to make it in iOS for the apple store but .ney MAUI MTA
admob is giving a lot of trouble making the app work, when i remove all the
plugins of MTAdmob it works again but when the plugin is loaded for the ads
the app crashes and does not give any error message I don't know maybe you
want to look into this with me? remote access to my PC maybe?

**Comment by marcojak** [comment]
After formatting my mac (old machine, many troubles) I've finally managed to test the app on my iPad (version 16.3) and it works fine.
I'm now updating my iPad to version 16.5 to check if by any chance the error is in the new iOS version.
My suggestion for now is to make sure you have the latest version of the plugin for MAUI (1.0.4), do a FULL clean & rebuild (also removing obj and bin folders) and try again....but make sure you have the latest version...the previous was was crashing on iOS devices (while was working on the simulator)

**Comment by darklance83** [comment]
Hi Marco,

I think this only happens on Visual Studio 2022. I read somewhere that it
works fine on MacOS so I was thinking maybe if I upload it and see how it
goes in hope it works when it's on the app store?

This is the version I have in visual studio 2022, I'll send my code below
so maybe you can spot the error faster than me.
[image: image.png]
[image: image.png]

There are in my CSPROJ

[image: image.png]

[image: image.png]

my App.xaml.cs

[image: image.png]

my AppDelegate.cs

[image: image.png]

My MainPage.xaml

[image: image.png]

My MauiPrograms.xaml.cs

[image: image.png]


This is what I get at the moment of debugging the iOS on iPadOS 16.5 (20F66)


Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/Microsoft.iOS.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Runtime.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Collections.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Runtime.InteropServices.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Threading.Thread.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Threading.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Net.Http.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Net.Primitives.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Numerics.Vectors.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Net.Sockets.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Drawing.Primitives.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Private.Uri.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/Xamarin.PreBuilt.iOS.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/Xamarin.iOS.HotRestart.Application.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/netstandard.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.IO.MemoryMappedFiles.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.IO.Pipes.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Memory.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Diagnostics.Tracing.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Collections.NonGeneric.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/Microsoft.Win32.Primitives.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Net.NameResolution.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Threading.ThreadPool.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Collections.Concurrent.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Diagnostics.Process.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.ComponentModel.Primitives.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.ComponentModel.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.ObjectModel.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Diagnostics.FileVersionInfo.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Reflection.Metadata.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Collections.Immutable.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Linq.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.IO.Compression.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Text.Encoding.Extensions.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Collections.Specialized.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Security.Cryptography.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Formats.Asn1.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Runtime.Numerics.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.ComponentModel.TypeConverter.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Runtime.Loader.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Text.RegularExpressions.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Reflection.Emit.ILGeneration.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Reflection.Emit.Lightweight.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Reflection.Primitives.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Net.Security.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Security.Claims.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Runtime.Serialization.Formatters.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Resources.Writer.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Xml.XDocument.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Private.Xml.Linq.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Private.Xml.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Diagnostics.TraceSource.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Diagnostics.DiagnosticSource.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Net.Quic.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.IO.Compression.Brotli.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Threading.Channels.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Net.NetworkInformation.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Reflection.Emit.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Linq.Expressions.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.ComponentModel.EventBasedAsync.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Console.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Data.Common.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Xml.ReaderWriter.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Xml.XmlSerializer.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Transactions.Local.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Diagnostics.Contracts.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Diagnostics.TextWriterTraceListener.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Diagnostics.StackTrace.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.IO.Compression.ZipFile.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.IO.FileSystem.DriveInfo.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.IO.FileSystem.Watcher.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.IO.IsolatedStorage.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Linq.Queryable.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Linq.Parallel.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Net.Requests.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Net.WebHeaderCollection.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Net.ServicePoint.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Net.HttpListener.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Net.WebSockets.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Security.Principal.Windows.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Net.WebClient.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Net.WebProxy.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Net.Mail.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Net.Ping.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Net.WebSockets.Client.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Reflection.DispatchProxy.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Runtime.CompilerServices.VisualC.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Runtime.Serialization.Primitives.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Runtime.Serialization.Xml.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Private.DataContractSerialization.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Runtime.Serialization.Json.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Threading.Overlapped.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Threading.Tasks.Parallel.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Web.HttpUtility.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Xml.XPath.XDocument.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Xml.XPath.dll [External]
Thread started:  #2
Thread started: .NET Timer #3
Thread started: <Thread Pool> #4
Thread started: .NET ThreadPool Gate #5
Thread started: <Thread Pool> #6
2023-06-01 17:46:29.194 Xamarin.PreBuilt.iOS[1197:272878] Content folder:
/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content

Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/dushi.dll
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Microsoft.Maui.Controls.dll
[External]
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Microsoft.Maui.dll
[External]
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Google.MobileAds.dll
[External]
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/MediaManager.dll
[External]
2023-06-01 17:46:29.195 Xamarin.PreBuilt.iOS[1197:272878] App path
/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/dushi.dll

2023-06-01 17:46:29.214 Xamarin.PreBuilt.iOS[1197:272878] AppDelegate name:
AppDelegate

Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Microsoft.Maui.Graphics.dll
[External]
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Plugin.MauiMtAdmob.dll
[External]
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Microsoft.Maui.Controls.Compatibility.dll
[External]
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/MediaManager.Forms.dll
[External]
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Microsoft.Extensions.DependencyInjection.Abstractions.dll
[External]
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Microsoft.Extensions.Logging.dll
[External]
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Microsoft.Extensions.Logging.Abstractions.dll
[External]
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Microsoft.Extensions.Options.dll
[External]
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Microsoft.Maui.Controls.Xaml.dll
[External]
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Microsoft.Extensions.Configuration.dll
[External]
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Microsoft.Extensions.Configuration.Abstractions.dll
[External]
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Microsoft.Extensions.Primitives.dll
[External]
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Microsoft.Extensions.Logging.Debug.dll
[External]
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Microsoft.Maui.Essentials.dll
[External]
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Firebase.Core.dll
[External]
Loaded assembly:
/private/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Microsoft.Extensions.DependencyInjection.dll
[External]
Resolved pending breakpoint for 'dushi.Program.Main(System.String[])' to
F:\GitHubRepository\MAUI.iOS\dushi\Platforms\iOS\Program.cs:10 [0x00000].
Loaded assembly: data-0x11110c000 [External]
Loaded assembly: data-0x111120000 [External]
2023-06-01 17:46:29.676 Xamarin.PreBuilt.iOS[1197:272878] Could not resolve
assembly Microsoft.VisualStudio.DesignTools.TapContract, Version=17.0.0.0,
Culture=neutral, PublicKeyToken=null. Details: Could not load file or
assembly
'/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Microsoft.VisualStudio.DesignTools.TapContract.dll'
or one of its dependencies.

2023-06-01 17:46:29.683 Xamarin.PreBuilt.iOS[1197:272878] Could not resolve
assembly Xamarin.HotReload.Contracts, Version=1.0.0.0, Culture=neutral,
PublicKeyToken=null. Details: Could not load file or assembly
'/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Xamarin.HotReload.Contracts.dll'
or one of its dependencies.

Resolved pending breakpoint for
'Xamarin.HotReload.HotReloadAgent.BreakpointSendToIde(System.String)' to
D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:423
[0x00000].
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Text.Json.dll [External]
Loaded assembly:
/private/var/containers/Bundle/Application/D09084FB-8262-4648-B3D6-5D4071D1F133/
dushi.app/System.Text.Encodings.Web.dll [External]
2023-06-01 17:46:29.815 Xamarin.PreBuilt.iOS[1197:272878] Could not resolve
assembly Xamarin.HotReload.Contracts, Version=1.0.0.0, Culture=neutral,
PublicKeyToken=null. Details: Could not load file or assembly
'/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Xamarin.HotReload.Contracts.dll'
or one of its dependencies.

Resolved pending breakpoint for
'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to
D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:418
[0x00000].
2023-06-01 17:46:29.818 Xamarin.PreBuilt.iOS[1197:272878] Could not resolve
assembly Microsoft.VisualStudio.DesignTools.TapContract, Version=17.0.0.0,
Culture=neutral, PublicKeyToken=null. Details: Could not load file or
assembly
'/var/mobile/Containers/Data/Application/A499B736-529A-45FA-91B7-0EF98336CA58/Documents/dushi.content/Microsoft.VisualStudio.DesignTools.TapContract.dll'
or one of its dependencies.

[0:] An error occurred: 'Object reference not set to an instance of an
object.'. Callstack: '   at
dushi.AppDelegate.FinishedLaunching(UIApplication application, NSDictionary
launchOptions) in
F:\GitHubRepository\MAUI.iOS\dushi\Platforms\iOS\AppDelegate.cs:line 18
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv,
IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type
delegateClass)
   at dushi.Program.Main(String[] args) in
F:\GitHubRepository\MAUI.iOS\dushi\Platforms\iOS\Program.cs:line 13
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1
args, BindingFlags invokeAttr)'
The app has been terminated.

**Comment by darklance83** [comment]
Works fine on android look below.

[image: image.png]

**Comment by alasz809** [comment]
I may be late to the party on this, but my ads would not show on physical device BUT would work in simulator.  The fix for me was to  Edit info.plist "Background Modes"
		-click info.plist/switch to Application mode in upper right
		-enable "backgrounds Modes"
			-check the "background processing" checkbox
This fixed it and I was able to see ads

**Comment by ottorinobruni** [comment]
I confirm the bug for iOS devices, when you publish your app in the app store and test via TestFlight, after the splash screen the app crashes. With simulators there are no problems.

**Comment by darklance83** [comment]
> 
Hi Alasz809,

Thanks for coming up with an alternative but these are the only options I am getting do you know how I can get the other options? see screenshot below please!

![image](https://github.com/marcojak/MTAdmob/assets/129236462/beab0484-3ed2-4d82-b259-45bb93e601d0)

**Comment by ottorinobruni** [comment]
> > 
> 
> Hi Alasz809,
> 
> Thanks for coming up with an alternative but these are the only options I am getting do you know how I can get the other options? see screenshot below please!
> 

Hi @darklance83 You can add UIBackgroundModes in this way but you will not solve this problem.
` 
       <key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
	</array>
`

**Comment by darklance83** [comment]
@ottorinobruni 

Hello,

So simply add this line <string>fetch</string> but ads will still not work when uploaded to the store? I am also having issues uploading the app to the store on MS studio 2022 do I need a Apple Mac OS to do this?

**Comment by ottorinobruni** [comment]
> @ottorinobruni
> 
> Hello,
> 
> So simply add this line fetch but ads will still not work when uploaded to the store? I am also having issues uploading the app to the store on MS studio 2022 do I need a Apple Mac OS to do this?

I use a Mac but I think the problem does not depend on our operating system. 
Using MauiMTAdmob and publishing an app on the Apple store the app crashes on startup. I reported the log above.

**Comment by peterrexj** [comment]
Still having issues with the latest version (1.9.0.6) on the VS 2022, Xamarin Forms iOS Physical device, 
just to confirm it fails only on the physical device and not in the simulator, this issue is stopping some releases, any update @marcojak ?

**Comment by jb11-repo** [comment]
Thanks @marcojak for this great lib. Confirming I also have this issue of crashing once pushed to a physical device through TestFlight. iOS simulator working fine. I see the splash screen but then it crashes. I've implemented a banner ad on all my pages in my app. Has anyone figured out a fix for this?

**Comment by darklance83** [comment]
@peterrexj  Hi Peter,

I gave up on this fix I went ahead and bought a MacOS laptop and started over again using Xcode and Android studio I created both app from scratch separately and it worked fine so I suggest give up on this add on cause it isn't going to work.

**Comment by marcojak** [comment]
Is this still an issue with the latest versions for Xamarin And MAUI?

**Comment by peterrexj** [comment]
> @peterrexj Hi Peter,
> 
> I gave up on this fix I went ahead and bought a MacOS laptop and started over again using Xcode and Android studio I created both app from scratch separately and it worked fine so I suggest give up on this add on cause it isn't going to work.

@darklance83, mate its too much to get a MacOS just for that, I thought to go on that path, but I don't have enough funds to get another OS :D 
Still fails but I caught that exception and added it to track (so no crash on the page) , meanwhile, it works on the published version and fails only on the TestFlight, so just live with that.
To debug on the physical devices, the whole ads thing is under a switch control, so whenever I try to test on a physical device  (iOS), I will switch off the ads and run the app.
It's just a work around and I know I cannot live long on this.
